FROM ubuntu:12.04.5
12.04 x64

# dependencias transverles
sudo locale-gen en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

sudo apt-get install autoconf binutils-doc bison build-essential flex
sudo apt-get install git
sudo apt-get install python-software-properties


sudo add-apt-repository ppa:cartodb/redis && sudo apt-get update
sudo apt-get install redis-server



